/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as EtudiantsRouteImport } from './routes/etudiants'
import { Route as FiscaliteRouteImport } from './routes/fiscalite'
import { Route as InvestissementsRouteImport } from './routes/investissements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as SocieteRouteImport } from './routes/societe'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantsRoute = EtudiantsRouteImport.update({
  id: '/etudiants',
  path: '/etudiants',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscaliteRoute = FiscaliteRouteImport.update({
  id: '/fiscalite',
  path: '/fiscalite',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestissementsRoute = InvestissementsRouteImport.update({
  id: '/investissements',
  path: '/investissements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const SocieteRoute = SocieteRouteImport.update({
  id: '/societe',
  path: '/societe',
  getParentRoute: () => rootRouteImport,
} as any)
const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/etudiants': typeof EtudiantsRoute
  '/fiscalite': typeof FiscaliteRoute
  '/investissements': typeof InvestissementsRoute
  '/login': typeof LoginRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/societe': typeof SocieteRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/etudiants': typeof EtudiantsRoute
  '/fiscalite': typeof FiscaliteRoute
  '/investissements': typeof InvestissementsRoute
  '/login': typeof LoginRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/societe': typeof SocieteRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/etudiants': typeof EtudiantsRoute
  '/fiscalite': typeof FiscaliteRoute
  '/investissements': typeof InvestissementsRoute
  '/login': typeof LoginRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/societe': typeof SocieteRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/depenses'
    | '/etudiants'
    | '/fiscalite'
    | '/investissements'
    | '/login'
    | '/rapports'
    | '/recettes'
    | '/societe'
    | '/tresorerie'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/depenses'
    | '/etudiants'
    | '/fiscalite'
    | '/investissements'
    | '/login'
    | '/rapports'
    | '/recettes'
    | '/societe'
    | '/tresorerie'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/depenses'
    | '/etudiants'
    | '/fiscalite'
    | '/investissements'
    | '/login'
    | '/rapports'
    | '/recettes'
    | '/societe'
    | '/tresorerie'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepensesRoute: typeof DepensesRoute
  EtudiantsRoute: typeof EtudiantsRoute
  FiscaliteRoute: typeof FiscaliteRoute
  InvestissementsRoute: typeof InvestissementsRoute
  LoginRoute: typeof LoginRoute
  RapportsRoute: typeof RapportsRoute
  RecettesRoute: typeof RecettesRoute
  SocieteRoute: typeof SocieteRoute
  TresorerieRoute: typeof TresorerieRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiants': {
      id: '/etudiants'
      path: '/etudiants'
      fullPath: '/etudiants'
      preLoaderRoute: typeof EtudiantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscalite': {
      id: '/fiscalite'
      path: '/fiscalite'
      fullPath: '/fiscalite'
      preLoaderRoute: typeof FiscaliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investissements': {
      id: '/investissements'
      path: '/investissements'
      fullPath: '/investissements'
      preLoaderRoute: typeof InvestissementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societe': {
      id: '/societe'
      path: '/societe'
      fullPath: '/societe'
      preLoaderRoute: typeof SocieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepensesRoute: DepensesRoute,
  EtudiantsRoute: EtudiantsRoute,
  FiscaliteRoute: FiscaliteRoute,
  InvestissementsRoute: InvestissementsRoute,
  LoginRoute: LoginRoute,
  RapportsRoute: RapportsRoute,
  RecettesRoute: RecettesRoute,
  SocieteRoute: SocieteRoute,
  TresorerieRoute: TresorerieRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
